apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-gt0j
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ihqs-tenant/rhtap-demo-app/hacbs-test-project-gt0j@sha256:5314f1f179083e58cd4f353d04e6dcd36c042b288882d978726515f383c0cf3a
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
